id: P088DB78A
initial_creation_type: ocr
source_metadata:
  volumes:
    727d4053454c40cb88780e9c615bec22:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོ་ལ་བསྟོད་པ་རྐང་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
